WP-API/node-wpapi

README.md
lib/shared/wp-request.js

Added possibility to use Cookie Auth when consuming the rest services in client scripts on the same site.
Localize your scripts with an object with root-url and nonce:
```
function my_enqueue_scripts() {
wp_enqueue_script( 'app', get_template_directory_uri() . '/assets/dist/bundle.js', array(), false, true );
wp_localize_script( 'app', 'WP_API_Settings', array(
'root' => esc_url_raw( get_json_url() ), 
'nonce' => wp_create_nonce( 'wp_json' ) ) 
);
}
add_action( 'wp_enqueue_scripts', 'my_enqueue_scripts' );
```
And use this nonce when initialising the library:
```
var WP = require( 'wordpress-rest-api' );
var wp = new WP({
endpoint: window.WP_API_Settings.root, 
nonce : window.WP_API_Settings.nonce
});
```

Enable Cookie auth with requests

---

lib/shared/wp-request.js
tests/lib/shared/wp-request.js

This sets the groundwork for being able to maintain an API base-relative client instance, while still permitting the handlers for native WP-API endpoints to retrieve the correct data, by giving them a mechanism by which to find their data at e.g. `endpoint/wp/v2/posts` instead of `endpoint/posts`.

Add .version and .namespace methods to wp-request

---

lib/media.js
lib/pages.js
lib/posts.js
lib/taxonomies.js
lib/types.js
lib/users.js
tests/lib/media.js
tests/lib/pages.js
tests/lib/posts.js
tests/lib/shared/wp-request.js
tests/lib/taxonomies.js
tests/lib/types.js
tests/lib/users.js
tests/wp.js

This continues the addition of native support for the WP API v2 series, by making all WordPress native type request methods (such as `.posts()` automatically set the "wp/v2" namespace and API version key in their request URL string.
To request one of these resources, we can now continue to specify the api client's endpoint as the json root, e.g. `yoursite.com/wp-json`, and the posts, pages, etc methods will automatically set the correct path to hit API v2 resources.
@tommedema and others who have experimented with using this alongside the API v2, please comment to let me know if this approach both makes sense, and works for you!

Use wp/v2/ endpoints for all native types

---

Gruntfile.js
package.json
tests/lib/shared/collection-request.js

This adds code-coverage reporting with [Istanbul](https://gotwarlost.github.io/istanbul/).
After running `npm test`, a coverage report will be printed:
A line-by-line report can be accessed by loading the generated `coverage/lcov-report` HTML report directory in a web browser.

Add code coverage reporting

---

.travis.yml
README.md
lib/shared/wp-request.js
package.json
tests/integration/posts.js
tests/unit/lib/shared/wp-request.js

The fact that 403's are returned for some requests and 401's for others is a result of https://core.trac.wordpress.org/ticket/35527
This adds documentation and an integration test around a full post create-update-delete cycle

Add integration tests for post creation & updating

---

.travis.yml

Based on commit message https://github.com/kadamwhite/wordpress-rest-api/commit/79be86917ffd83929275174f92a3351a608742e3 _"Travis should test recent stable node versions, as well as iojs"_ I've updated the NodeJS test matrix:
• iojs is for all intensive purposes deprecated, it was merged back into the v4 branch of NodeJS https://iojs.org/en/
• The latest LTS (Long Term Support) version of NodeJS is v4.2.4, using the `4` alias will always use the latest 4.x.x branch
• The latest "stable" is the 5.x branch which is currently v5.4.1, again using `5` will always test the latest v5.x.x branch. (Note Also the NVM alias `stable` is deprecated, https://github.com/creationix/nvm#usage)

Test on Node.js v0.12.x, v4.x, and v5.x

---

.jscsrc
Gruntfile.js
lib/taxonomies.js
tests/integration/categories.js
tests/integration/tags.js
tests/integration/taxonomies.js
tests/unit/lib/taxonomies.js
tests/unit/wp.js
wp.js

Support default taxonomy collections using v2 endpoints.
Many of these changes are adapted from work by @jasonphillips [in his fork of the project](https://github.com/jasonphillips/wordpress-rest-api/commit/cdc171d749c27d655f2cfcad446f4cbec2660219) -- full props to him for pioneering how to adapt the existing infrastructure to the new endpoints.
Tasks before PR can land:
Related work, to be executed separately:
- Update library to support querying for the terms associated with a post (skate to where the puck will be: depends on WP-API/WP-API#2063)
- Verify (via integration test) that library works with hierarchical and non-hierarchical custom taxonomies

Support v2 Taxonomy Routes

---

lib/shared/alphanumeric-sort.js
lib/shared/collection-request.js
lib/shared/wp-request.js
tests/unit/lib/shared/collection-request.js
tests/unit/lib/shared/wp-request.js

Parameters are more generic than filters: they can be useful on almost any API resource if they are used to specify context or to trigger data embedding. Moving these from CollectionRequest means that they will also be available on WPRequest derivatives like the paging `.next` and `.prev` requests, enabling consumers of the pagination queries to utilize methods like `.embed()`.

Move param() handling and renderQuery method to WPRequest

---

lib/taxonomies.js
tests/integration/categories.js
tests/integration/posts.js
tests/unit/lib/taxonomies.js

This adds support for fetching the terms for a given post, per the changes introduced to WP-API in v2 beta 11.
`.post()` is not a viable chaining method because that maps to sending a POST request: `forPost()` is a more readable, declarative way to specify the post for which to retrieve terms.

Add forpost method to tax collections

---

lib/shared/collection-request.js
tests/unit/lib/shared/collection-request.js

V2 Beta 11 added support for a slug property (see discussion started in WP-API/WP-API#2065) -- we should use that instead of the `filter[name]` "shim" for WP_Query.
This PR updates the API client to set the `slug` parameter instead of the `name` filter, and makes `name()` call through to `slug()` as opposed to the other way around.

Alter .slug() collection filter method to use new ?slug= parameter

---

README.md

As I was setting up a project locally, I was not able to get the example to work, then I figured out I needed to add `wp-json` to the end of the endpoint URL.

Add wp-json to endpoint URL in README example

---

lib/shared/wp-request.js
tests/unit/lib/shared/collection-request.js
tests/unit/lib/shared/wp-request.js

Do not include empty parameters in the generated query string.
Do not inspect `_params` when testing query string generation: instead, inspect the generated URL (which will be a public API eventually). `_params` is an internal implementation detail and should not be part of our tested interface.

Improve query parameter generation

---

README.md
lib/posts.js
lib/types.js
tests/unit/lib/posts.js
tests/unit/lib/types.js
tests/unit/wp.js
wp.js

- The route for `.types()` is no longer nested under `/posts`
- The path has been updated; integration tests TODO
- `/comments` and `/statuses` are no longer nested under `/posts/:id`
- These chaining methods have been removes
- It is no longer possible to access CPT items under `/posts`
- The `.type` chaining method has been removed
- The `wp.registerType` method has been removed temporarily pending support for top-level CPT collections
- Date query code was duplicated between PostsRequest & CollectionsRequest
- The PostsRequest code has been removed

Remove outdated v1 code

---

tests/integration/posts.js

From https://make.wordpress.org/core/2016/02/09/wp-rest-api-version-2-0-beta-12/ :
> Returns original resource when deleting PTCU. Now that all resources require the `force` param, we don’t need to wrap delete responses with the trash state.
What this means is that we should get the original, unaltered post back in the event that the delete action succeeds, and an error if it does not succeed: the integration test has been modified to rigorously test the side-effects of deletion, by querying for the post to validate that trashing removes it from public results and deletion removes it permanently.

Update post deletion integration test for breaking beta 12 changes

---

tests/integration/categories.js

The key has changed to "wp:term"

Update relation name in embedded category test

---

lib/comments.js
tests/integration/comments.js
tests/unit/lib/comments.js
wp.js

Comments are not currently supported as a top-level endpoint.
This adds a basic `/comments` endpoint handler, which can
- Retrieve a paged collection of comments
- Retrieve a specific comment by ID
- Retrieve comments by their parent post or page via the `.forPost()` query parameter method
Unit tests and integration tests have been added to validate the enumerated behaviors of the endpoint handler work as expected.
Further [comment query parameters](http://v2.wp-api.org/reference/comments/) will follow in subsequent PRs, possibly following #145.

Add wp/v2/comments endpoint handler and corresponding tests

---

tests/integration/posts.js

This should have surfaced the issue I believed was the cause of #146, but this test passes without a fuss. I am unclear now on what the actual cause of #146 might be.
Either way, this is good functionality to exercise.

Add integration test validating bound-get-callback behavior

---

README.md
lib/endpoint-factories.js
lib/endpoint-request.js
lib/path-part-setter.js
lib/resource-handler-spec.js
lib/route-tree.js
lib/util/named-group-regexp.js
lib/wp-register-route.js
tests/.jshintrc
tests/integration/posts.js
tests/unit/lib/util/named-group-regexp.js
tests/unit/lib/wp-register-route.js
wp.js

This supersedes both #144 and #158 by providing a method that developers can use to arbitrarily support any endpoint.
---------------------------------------
Support for Custom Post Types is provided via the `.registerRoute` method. This method returns a handler function which can be assigned to your site instance as a method, and takes the [same namespace and route string arguments as `rest_register_route`](http://v2.wp-api.org/extending/adding/#bare-basics):
```js
var site = new WP({ endpoint: 'http://www.yoursite.com/wp-json' });
site.myCustomResource = site.registerRoute( 'myplugin/v1', '/author/(?P<id>)' );
site.myCustomResource().id( 17 ); // => myplugin/v1/author/17
```
The string `(?P<id>)` indicates that a level of the route for this resource is a dynamic property named ID. By …

Add wp.registerRoute() method to define custom endpoints

---

README.md

- Also better explains that creating and updating posts are generalizable actions that can be executed against all resources

Remove deprecated (or temporarily removed) route examples from docs

---

.gitattributes
lib/autodiscovery.js
lib/constructors/wp-request.js
lib/endpoint-factories.js
lib/wp-register-route.js
package.json
tests/integration/autodiscovery.js
tests/integration/posts.js
tests/unit/lib/autodiscovery.js
tests/unit/wp.js
wp.js

Contains unit tests & integration tests, with ~85% coverage
Closes #74
The API this provides is as follows:
```js
var apiPromise = WP.discover( 'http://my-site.com' );
apiPromise.then(function( site ) {
// If default routes were detected, they are now available
site.posts().then(function( posts ) { console.log( posts ); }); // etc
// If custom routes were detected, they can be accessed via .namespace()
site.namespace( 'myplugin/v1' ).authors()
.then(function( authors ) { /* ... */ });
// Namespaces can be saved out to variables:
var myplugin = site.namespace( 'myplugin/v1' );
myplugin.authors().id( 7 ).then(function( author ) { /* ... */ });
});
```

Support Autodiscovery

---

README.md

Missed this TODO in #181, adding now

Document autodiscovery methods (from #181)

---

README.md
lib/constructors/wp-request.js
tests/integration/posts.js
tests/unit/lib/constructors/wp-request.js

This one has been a long time coming: POSTing a post to the posts endpoint is a linguistic nightmare, and HTTP verbs are part of the API interface that is best kept away from the users.
This alters all of the existing GET, POST, PUT, DELETE and HEAD methods to be (semi)private and prefixed by `_http`, e.g. `_httpDelete`: The public interfaces for these (`.get`, `.create`, `.update`, `.delete` and `.headers`).
`.post` and `.put` are maintained for the time being for back-compat but will be removed in 1.0.

Switch .post() and .put() to .create() and .update()

---

package.json

This release makes some key changes, adds some essential functionality, and re-wires things under the hood. I am unilaterally adopting the model of naming releases after albums, because I am releasing this in Vienna and "Mozart's House" by Clean Bandit (New Eyes, track 1) has been stuck in my head throughout WordCamp Europe.
**Autodiscovery**
Autodiscovery is now supported via the `WP.discover` method (#181)
**Bootstrapping**
If you already have the API response object you want to bootstrap with, the `.routes` property from it can now be passed in when calling `WP.site` or instantiating a `new WP` object (also #181, documented #182):
```js
var site = WP.site( 'http://my-endpoint.com/wp-json', endpointJSON.routes );
```
A script to ease the process of downloading this JSON object was added …

Release v0.8.0 "New Eyes"

---

.gitignore
lib/autodiscovery.js
lib/constructors/wp-request.js
lib/data/simplify-object.js
lib/endpoint-factories.js
lib/mixins/filters.js
lib/mixins/parameters.js
lib/path-part-setter.js
lib/route-tree.js
lib/util/ensure.js
lib/util/key-val-to-obj.js
package.json
tests/integration/autodiscovery.js
tests/integration/categories.js
tests/integration/posts.js
tests/unit/lib/autodiscovery.js
tests/unit/lib/util/key-val-to-obj.js
webpack.config.js
webpack.config.minified.js
wp.js

This PR
- Adds a [Webpack](webpack.github.io) build to bundle the library code into `/browser/wpapi.js`
- Switches from [Bluebird](http://bluebirdjs.com/docs/getting-started.html) to [es6-promise](https://www.npmjs.com/package/es6-promise) for all our Promise-polyfilling needs, to minimize the size of the bundled code
- Switches from using the full Lodash (at an outdated version, no less) to using only the three lodash sub-modules that are needed to make this library's code function (`reduce`, `uniq` and `union`), to minimize the size of the bundled code

Add a build process to create a bundle for browser use

---

wp.js

Currently if you pass a non-string value as the `endpoint` you won't receive the nice `'options hash must contain an API endpoint URL string'` warning, but instead the library will throw on attempting to invoke `replace` on whatever that value is.
Small commit to fix this by checking that `endpoint` not only exists, but that it is a string.

Check existence of `options.endpoint` by its type

---

README.md
lib/constructors/wp-request.js

This adds a `.file` method which may be chained onto a `.media()` handler to upload a file attachment when `.create`ing a new media record. Documentation for this method has been added to the README and inline docs; still needs tests.
For #116, #153, #185

Add method to attach a file when creating a media object

---

lib/endpoint-request.js
tests/integration/posts.js
tests/unit/lib/wp-register-route.js

As setters are inferred from the shape of the API routes, there are situations where the names parts of a route will result in setter fn names that conflict with (i.e. are the same as) preexisting methods on the WPRequest object. The `.post` query terminator that triggers a POST request is a good example, as the part of the route indicating post ID for e.g. a revision is named as "post".
In this situation we skip assigning that setter, as in most cases it will not preclude accessing that resource through other means (the .id method will set the post ID in this case, and the revisions method will set the revision ID). Historically, however, we did log a warning when this occurred, to note that certain methods may not be available as expected.
This warning is distracting and causes concern …

Do not log a warning when skipping preexisting methods during discovery

---

README.md
lib/resource-handler-spec.js
tests/integration/posts.js
tests/unit/lib/wp-register-route.js

The logic used to create setter names for path parts within a resource handler incorrectly assumed that all path part components should be lowercased before being converted from snake_case to camelCase. If a resource already employed a camelCase component (and it is perfectly valid to do so), then the setter for thatComponent would be created as `thatcomponent`, not `thatComponent`. This is unintuitive behavior (and actually raises the question of whether the token should be mutated at all), so this PR removes the offending `toLowerCase` method and documents the naming conversion logic in the readme.
Fixes #198, props @joneslloyd for the bug report

Do not unnecessarily lowercase path part setter names

---

documentation/_posts/2016-08-15-create-a-post-with-featured-media.md
tests/integration/posts.js

This closes #153 by adding an integration test demonstrating the process to create a post with taxonomy terms and featured media, and a human-facing user guide for the same.

Create post integration test and guide

---

build/scripts/release-docs.js
package.json

This commit replaces the temporary placeholder `npm run release-docs` command with a fully-functional script which will automate the process as it currently stands. This is only tested on OSX and should be adjusted to be more platform-independent if and when other committers are added to this project.

Automate the documentation release process with a script

---

README.md
lib/mixins/index.js
lib/mixins/parameters.js
tests/integration/posts.js
tests/unit/lib/mixins/parameters.js

These top-level query parameters are supported by all built-in collections of dated resources (posts, media, comments, etc).
If a Date object is provided, it is converted to a full ISO8601 string before being sent to the API.
Closes #179

Add .before and .after parameter mixins

---

README.md
lib/constructors/wp-request.js
tests/integration/autodiscovery.js
tests/unit/wp.js
wp.js

As noted in #216, the process of authenticating after autodiscovery is not obvious: it is technically possible, but the manner documented uses
```js
WP.discover( 'http://my-site.com' ).then(function( site ) {
// Call .auth method on individual query
return site.users().auth( credentials ).me();
}).then(function( user ) { /* ... */ });
```
which is verbose and not obvious in the way that instantiating a WP instance with authentication "baked in" can be.
To resolve the issue, this PR exposes & documents the (existing) `.auth` method on the WP site instances themselves: this method is identical to WPRequest's `.auth`, but sets the provided options on the WP site client instance itself so that they will apply to _all_ subsequently-generated API requests.
The easiest way to use authentication …

Allow authentication credentials to be set after autodiscovery

---

README.md
lib/constructors/wp-request.js
tests/integration/autodiscovery.js
tests/unit/lib/constructors/wp-request.js
tests/unit/lib/mixins/filters.js
tests/unit/lib/wp-register-route.js
tests/unit/route-handlers/comments.js
tests/unit/route-handlers/media.js
tests/unit/route-handlers/pages.js
tests/unit/route-handlers/posts.js
tests/unit/route-handlers/taxonomies.js
tests/unit/route-handlers/types.js
tests/unit/route-handlers/users.js
tests/unit/wp.js

`._renderURI` is arguably the most important single method this library provides; it would be possible (and should eventually be easy) to use the query builder interface independently of any specific HTTP library like superagent, _e.g._ if you wanted to use jQuery or `fetch` to send requests, so long as you have the ability to get at the full, rendered URI for the API query you need to execute.
As such, having this be exclusively "private" (or as private as `_methods` ever can be) functionality has proved confusing. Exposing `_renderURI` as `.toString` makes it a first-class public citizen of the library, and makes it more obvious how the query methods lead to the generation of a URI that is then converted into an HTTP request action by one of the HTTP terminator methods.
`_requestURI` is …

Promote _renderURI to a public api & rename to toString

---

lib/constructors/wp-request.js
lib/endpoint-factories.js
lib/http-transport.js
lib/util/check-method-support.js
lib/util/http-transport.js
tests/integration/custom-http-transport.js
tests/unit/lib/constructors/wp-request.js
tests/unit/lib/wp-register-route.js
tests/unit/route-handlers/comments.js
tests/unit/route-handlers/media.js
tests/unit/route-handlers/pages.js
tests/unit/route-handlers/posts.js
tests/unit/route-handlers/taxonomies.js
tests/unit/route-handlers/types.js
tests/unit/route-handlers/users.js
tests/unit/wp.js
wp.js

WPRequest currently does two things: It builds a string, then it allows HTTP requests to be submitted against the resource that URI string represents. The latter part of that behavior will benefit from being pluggable, as described in #211 and #213.
Exposing WPRequest itself is something I would like to avoid to keep the core workings of the library (its URI-builder behavior) safe from unexpected modification; but exposing the HTTP behavior and enabling it to be customized or extended not only solves the issue expressed in the linked issues around cache implementation, but also provides a better interface for specifying bespoke authentication behavior.
To that end, this commit moves WPRequest's HTTP logic into a separate http-transport.js module, and injects a _copy_ of that module's …

Permit custom functionality to be injected into HTTP transport actions

---

README.md
tests/unit/wp.js
wp.js

This follows #220 by providing a method by which transport functions can be set on a preexisting `WP` instance object, such as one returned through the auto-discovery flow. Documentation around HTTP behavior customization and extension has been added to the README.

Implement `.transport()` prototype method & document transport customization

---

README.md
build/grunt/yuidoc.js
documentation/index.html.combyne
lib/wp-register-route.js
package.json

v0.10 standardizes the name of the constructor exposed by this module as "WPAPI", and creates a seam through which HTTP interactions can be customized or overridden. This release is named for Brazilian DJ Gui Boratto's fourth studio album _Abaporu_ (Kompakt, 2014).
**Module Naming**
The constructor exposed by this module should be referred to as `WPAPI` in all cases. This has been updated across the documentation site, source code, and examples within code comments.
There is remaining inconsistency throughout the docs & test suite between whether an _instance_ of `WPAPI` is referred to as `wp` or as `site`; this will not be addressed at this time, the identifier used to hold the WP site client instance is left up to the library consumer.
**Custom HTTP Transport Behavior**
Custom HTTP …

Release v0.10.0 "Abaporu"

---

README.md

README.md was mistakenly referring to `lib/data/generate-endpoint-request.js`, which was renamed to `lib/data/generate-endpoint-response-json.js`

Fix Broken reference/reference on README

---

tests/integration/comments.js

Comment default sort order was changed to be more consistent with other endpoints (and with WP_Comment_Query), which broke our integration test because the test was written for the previously-default "asc" ordering.

Update comments integration tests to work on latest API

---

README.md
lib/mixins/parameters.js
tests/unit/lib/mixins/parameters.js

This is an anticipatory change for compatibility with the latest develop branch of the REST API plugin, which added support for a "sticky" param used to either return only, or else no, sticky posts, depending on what boolean value is passed.
See WP-API/WP-API#2708

Add parameter setter for .sticky()

---

README.md
lib/mixins/parameters.js
tests/integration/posts.js
tests/unit/lib/mixins/parameters.js

Password-protected posts will soon be supported in the API, and this PR adds a .password() method for use with any endpoints that support the "password" parameter.
Several assertions disabled to permit test suite to work with stable OR develop branches of the API plugin.

Add `.password()` mixin for posts endpoint for password-protected posts

---

package.json

The theme for v0.11 is better parameter handling. Several parameters are now supported that apply to all default content routes, and this release also features a [complete overhaul][a] of the handling for registering mixins and custom query parameter setters with `.registerRoute()`.
**Parameter convenience methods**
`.order()`, `.orderby()`, `.offset()`, `.exclude()`, `.include()`, `.page()`, `.perPage()` and `.slug()` are now supported for _all_ request handlers generated by this library, not just for some resources.
**Setting Parameters on Custom Routes**
The `.param( name, val )` method is always available for custom route handler instances, but the convenience of `.filter` and other overloaded setters was not available to custom routes without some sleuthing through the code for this …

Release v0.11.0 "Super"

---

tests/unit/lib/constructors/wp-request.js
tests/unit/route-handlers/comments.js
tests/unit/route-handlers/media.js
tests/unit/route-handlers/pages.js
tests/unit/route-handlers/posts.js
tests/unit/route-handlers/taxonomies.js
tests/unit/route-handlers/types.js
tests/unit/route-handlers/users.js
tests/unit/wpapi.js
wpapi.js

Up to now, if a username and password (or nonce) were supplied when instantiating a WPAPI instance, those credentials would not be used by default. This meant that these requests would be handled differently in terms of authentication, despite having all the same information:
```js
// Authenticated
site = new WPAPI({
endpoint: 'some.website.com/wp-json'
}).auth({
username: 'bananayoshimoto',
password: 'kitchen'
});
site.posts()...
// NOT Authenticated
site = new WPAPI({
endpoint: 'some.website.com/wp-json',
username: 'bananayoshimoto',
password: 'kitchen'
});
site.posts()...
```
The consumer of the API must have called `.auth()` at some point on the parent WPAPI object or the instantiated request chain in order for authentication to be used on the request.
This is unintuitive and …

Always use authentication when credentials are available

---

lib/constructors/wp-request.js
tests/unit/lib/constructors/wp-request.js
tests/unit/wpapi.js

The string username & password signature for the `.auth()` method (both for WPRequest-derived handlers & WPAPI instances itself) has been deprecated for the last release or so because it offers less flexibility vs explicit parameter naming. Were we to add, say, OAuth support, we would want to be able to specify a token and secret value, but would not want them to be confusable with the less-recommended Basic Auth scheme. Removing the signature that uses unnamed strings disambiguates in a future-oriented way.

Breaking: Remove deprecated `.auth( 'user', 'pass' )` method signature

---

lib/constructors/wp-request.js
tests/unit/lib/constructors/wp-request.js

Deprecated since v0.8.0: use `.create()` and `.update()` instead

Breaking: Remove deprecated WPRequest `.post`/`.put` methods

---

lib/constructors/wp-request.js
tests/unit/lib/constructors/wp-request.js

Deprecated since v0.9.2 & v0.11 respectively
Use `.toString()` and the consistently-named `.slug()` method instead

Breaking: remove deprecated WPRequest `._renderURI()` & `.name()`

---

README.md
lib/mixins/index.js
lib/mixins/parameters.js
tests/integration/categories.js
tests/integration/comments.js
tests/unit/lib/mixins/parameters.js

Now that WPRequest's `.post` has been removed (in favor of `.create`), we can reinstate the most-obviously-named handler for filtering on the `?post` query parameter.
`.forPost()` is now deprecated and will be removed in a future release

Rename `.forPost` mixin to just `.post`; deprecate `.forPost`

---

README.md

To get it clear that it can use Buffer, not only file path.
Fix #245

Readme: add syntax description for Uploading Media

---

README.md

Unifying @Ohar's added documentation with the style of other readme sections, and noting the client-side option in the initial list of `file` method arguments

Readme: reformat media section for reading flow

---

README.md

Thank you @joaojeronimo for identifying this issue.
The documentation for querying for custom taxonomy terms is outdated. Term collections are now top-level routes on the `/wp/v2` namespace, and are no longer nested within their parent taxonomy. The result of this is that the nesting operators documented in the README are pointing to a route that no longer exists &mdash; for the custom taxonomy "genre", for example, if registered with a `rest_base` argument like so:
```php
register_taxonomy( 'genre', array( 'album' ), array(
'hierarchical'      => true,
'show_ui'           => true,
'show_admin_column' => true,
'query_var'         => true,
'rewrite'           => array( 'slug' => 'genre' ),
'show_in_rest'      => true,
'rest_base'         => 'genres',
'rest_controller_class' => …
```

Update outdated custom taxonomy term handler documentation (fixes #251)

---

tests/integration/media.js

This accounts for
- changes to the integration suite's sample data file (which has been moved into the [wpapi-vagrant-varietal](https://github.com/kadamwhite/wpapi-vagrant-varietal) repo to "pin" the content, _vs_ using an uncontrolled, changing external source)
- Updates to how response objects are structured in the 4.7 RC api endpoints

Update media tests to reflect late-cycle 4.7 API changes

---

lib/resource-handler-spec.js

According with https://developer.wordpress.org/reference/functions/register_post_type/#parameters custom post types can have both underscore and hyphens, resulting in endpoints like `my_content `or `my-content`. Current API supports only underscore.
I'm not a WP or a Node developer, but I think this should be either addressed or at least documented.
A temporary workaround is to call the endpoint with `site['my-content'].get()`.
This patch add hyphens supports on routes names replacing.
Ideally the exact regexp should be `[^a-z]+`, in order to cover any future changes and plugins creating weird endpoints.

Supporting hyphens on endpoints

---

lib/constructors/wp-request.js
lib/data/simplify-object.js
lib/endpoint-factories.js
lib/http-transport.js
lib/route-tree.js
lib/util/object-reduce.js
package.json
tests/integration/media.js
tests/integration/posts.js
tests/unit/lib/util/object-reduce.js
wpapi.js

As identified by [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer), lodash.reduce is the largest single dependency within the wpapi library (390.08kb overall):
Lodash.reduce is powerful, but has more code and optimizations than are needed for our specific use-case of reducing over an object of key-value pairs in the manner of Array#reduce.
This PR replaces Object.reduce with an API-identical method objectReduce, which handles the simple case of iterating over basic objects containing only own-property key-value pairs. This functionality is sufficient for the needs of node-wpapi, as Array#reduce itself is used for reduction over arrays and we are generally iterating over basic route definition JS objects, not complex instance objects.
After this change our …

Implement basic objectReduce() function to replace lodash.reduce

---

lib/autodiscovery.js
tests/integration/autodiscovery.js
tests/unit/lib/autodiscovery.js
tests/unit/lib/mixins/filters.js
tests/unit/wpapi.js
wpapi.js

In #181 auto-discovery was added that permits a consumer of this library to automatically locate the API root for a given WordPress site (specified by URL), and in most cases to automatically detect & initialize specific route handlers for the API routes available on that site.
However, these methods were never updated to account for #221, which added the ability to replace the default HTTP transport (superagent) with a custom implementation or a wrapper. This meant that even if the consumer had specified their own transport, for example jQuery, there would still be a dependency on superagent should they wish to use the auto-discovery capabilities of the library.
This PR updates the auto-discovery logic to use the same HTTP transport layer as the rest of the client, which has the added …

Make requests using HTTP transport during auto-discovery process

---

lib/http-transport.js
tests/integration/media.js
tests/integration/posts.js

This simplifies the returned object coming back from the API when an API error is encountered during a request: rather than returning the full superagent object, only the API error body is returned. This makes it easier for a consuming client to check the response against the expected codes without caring about the structure of the HTTP transport object.
The most important implication of this is that now, if a consumer defines their own transport, they have but to return the error body and responses from their transport will be functionally identical to responses from other transports, where before the response object was transport-specific. This is critical in order to make transport substitution minimally impactful to a consuming application.
Closes #124

Return API error body, not full superagent response

---

README.md
lib/mixins/index.js
lib/mixins/parameters.js
tests/integration/posts.js
tests/unit/lib/mixins/parameters.js
tests/unit/route-handlers/posts.js

This PR adds a `.status()` query method for setting one or more statuses to return for endpoints that differentiate based on status, such as Posts (fixes #264). It also allows the `.password` and `.sticky` mixins to be properly applied; they were not previously auto-set when working with a collection that supports those parameters as they were not included in the mixin index.
All three parameters are now tested consistently, & all are documented in the README file.

Add `.status()` query method & fix mixin application bug

---

lib/http-transport.js
tests/integration/error-states.js

Only pass API errors through; return transport-level errors as-is

---

README.md
tests/integration/settings.js

Adds documentation and integration tests to ensure that `.settings()` can be used to read and write site settings when authenticated.
Fixes #263

Test & document .settings() route handler

---

lib/constructors/wp-request.js
lib/mixins/parameters.js
package.json
tests/unit/lib/constructors/wp-request.js
tests/unit/lib/mixins/parameters.js

The third "merge" argument in `.param( key, val, merge )` has been on the chopping block for two months and is now being removed prior to the 1.0 release.
WPRequest instances are intended to be transient: It is much easier to understand building a single array of values, and then call `.param( 'key', valuesArr )` once at the end, than it is to mentally keep track of calling `.param( 'key', value, true )` multiple times.
It is also one of the only mysterious boolean arguments in the entire library, and we normally aim to avoid those.
It is _also_ only used in one place (the `.parent` mixin), and is the only place the `lodash.uniq` NPM dependency is used within node-wpapi. Removing the argument allows us to simplify code in several places and permits the removal of that dependency library, …

Breaking: Remove "merge" argument from `.param` method (Closes #227)

---

README.md
lib/constructors/wp-request.js
wpapi.js

Begin updating readme & doc blocks for v1.0
- Remove beta notices
- Update supported version to point to 4.7
- Reword introduction to clarify "isomorphic" capability
- Link to developer.wordpress.org, not wp-api.org

v1.0 pre-flight cleanup

---

README.md

Fixes #293
The documentation in the README (and therefore the node-wpapi.wp-api.org site) is out-of-date: it points to the legacy wp-api.org instead of the new developer.wordpress.org/rest-api handbook, and it references plugin-era methods instead of the new, standardized core methods for cookie authentication.
Props @bkirby989 for reporting this discrepancy.

Update README for 4.7, re-point links to reference developer.w.org

---

README.md

As noted in #303, our documentation does not cover how to enable the REST API to be discovered with a cross-origin request. This PR adds a new section to the readme to explain the process.
Fixes #303

Add README section explaining how to enable auto-discovery over CORS

---

README.md
lib/constructors/wp-request.js
lib/http-transport.js
tests/integration/custom-http-headers.js
tests/unit/lib/constructors/wp-request.js
tests/unit/wpapi.js
wpapi.js

In response to #299, #312, and #314, this introduces a new .setHeaders() prototype method for both WPAPI and WPRequest. `.setHeaders()` allows a single WPRequest, or all requests generated from a WPAPI site client instance, to be augmented with one or more custom HTTP headers. Providing this functionality allows consumers of the wpapi library to utilize custom authentication schemes (such as JWT) with the Authentication header, to specify the preferred language of the response endpoints with the Accept-Language header, and so on. Providing a general-purpose interface is preferred in place of specifically implementing individual methods for JWT auth, language preferences, or other specific headers that a consumer of this library may want to send.
Closes #299, fixes #312, fixes #314
If you …

Implement a `.setHeaders()` method for WPAPI and WPRequest objects

---

lib/route-tree.js
lib/util/named-group-regexp.js
lib/util/split-path.js
tests/unit/lib/util/named-group-regexp.js
tests/unit/lib/util/split-path.js
tests/unit/lib/wp-register-route.js

Some plugins, most notably Jetpack, contain named capture groups in their route definitions with regular expressions which include forward slash characters. Our naive method of creating the path part hierarchy was to `.split( '/' )`, which would break these regular expressions in two and cause an error when the route object is being built.
To work around this, we can separate out the named capture groups and only `.split( '/' )` the remaining leftover, non-capture-group parts of the path string.
Fixes #310

Avoid errors when named capture groups contain forward slashes

---

lib/http-transport.js
tests/integration/posts.js

When we create the WPRequest object to handle the previous or next pages of a collection (when available), we were passing only the endpoint and the HTTP Transport object -- this creates a valid WPRequest object, but authentication parameters are then not passed on to the new request objects. This PR updates the logic within the transport to maintain any set options on the request, overwriting only the endpoint URI, so that authentication will be maintained when paging through a collection.
Fixes #325 
props @motleydev

Maintain authentication when making paginated .prev/.next requests

---

README.md

`root` should be replaced with `endpoint`.

Incorect key name in "Cookie Authentication" example

---

lib/autodiscovery.js
lib/constructors/wp-request.js
lib/endpoint-request.js
lib/http-transport.js
lib/mixins/filters.js
lib/util/unique.js
package.json
tests/integration/autodiscovery.js
tests/integration/media.js
tests/unit/lib/constructors/wp-request.js
tests/unit/lib/mixins/filters.js
tests/unit/lib/mixins/parameters.js
tests/unit/lib/util/unique.js
webpack.config.minified.js

- Add Webpack Bundle Analyzer and a `npm run build:stats` package script
- Switch from `lodash.uniq` to custom modern JS `Set`-based `unique()` implementation
- Standardize on `li` library for link header parsing
- Remove unused dependencies
- Remove unneeded url transformation and `mergeUrl` method in http transport code (had no effect)
- Switch to `class` syntax instead of using `util.inherits`

Reduce bundle size

---

lib/http-transport.js
tests/integration/categories.js
tests/integration/comments.js
tests/integration/media.js
tests/integration/pages.js
tests/integration/posts.js
tests/integration/tags.js

#332 describes situations where the library will think that there is no paging information available, despite those headers being present in the received response. While I have not been able to replicate the exact scenario, two possibilities which suggest themselves are that Superagent does not consistently lowercase the header property names (causing a lookup failure), and that the total and totalPages values may be improperly parsed (due perhaps to carriage returns, etc). This PR adds a defensive guard against capitalization by ensuring that every key on the headers object is assigned as its lowercase equivalent, so that a `headers[ 'X-Capital-Header' ]` will get duplicated as `headers[ 'x-capital-header' ]`.
We also add type coercion to convert the total and total pages headers into …

Safeguard against custom response header inconsistencies

---

README.md
lib/constructors/wp-request.js

No filename can be determined from a buffer object, which causes an `Error: No data supplied` warning. Adding a specific error check makes this more obvious and will allow consuming developers to quickly identify and resolve the issue.
Fixes #344
props @cungminh2710, @mvhirsch

Throw error if name argument is not provided to .file() when uploading a buffer

---

lib/util/named-group-regexp.js

I modified the regex so it can correctly capture plugins Rest API Routes.
I've tested autodiscovery on a WordPress 5.5.3 and the autodiscovery works.
So far i'm not proficients with node to get test modified to check if it correctly works in every situations or on new versions of WP by now 5.6.*
Thanks

Plugin route fix
